create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  category text not null,
  price_inr integer not null check (price_inr >= 0),
  image_url text,
  stock_quantity integer not null default 0 check (stock_quantity >= 0),
  is_new boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_email text,
  customer_phone text not null,
  delivery_address text not null,
  notes text,
  status text not null default 'new' check (status in ('new', 'contacted', 'payment_pending', 'paid', 'making', 'shipped', 'completed', 'cancelled')),
  total_inr integer not null default 0 check (total_inr >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id),
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price_inr integer not null check (unit_price_inr >= 0),
  created_at timestamptz not null default now()
);

create table public.order_requests (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  customer_name text not null,
  phone text not null,
  shipping_address text not null,
  budget_inr integer not null check (budget_inr >= 0),
  timeframe text not null check (timeframe in ('2_weeks', '3_weeks', '4_weeks', '5_weeks', 'take_your_time')),
  notes text,
  status text not null default 'new' check (status in ('new', 'contacted', 'accepted', 'declined', 'completed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

create policy "Public can view active products"
on public.products for select
using (is_active = true);

create policy "Public can create orders"
on public.orders for insert
with check (true);

create policy "Public can create order items"
on public.order_items for insert
with check (true);

create index products_category_idx on public.products(category);
create index products_active_idx on public.products(is_active);
create index orders_status_idx on public.orders(status);
create index order_items_order_id_idx on public.order_items(order_id);
create index order_requests_status_idx on public.order_requests(status);
create index order_requests_created_at_idx on public.order_requests(created_at);

create table public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table public.site_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;
alter table public.site_settings enable row level security;

create policy "Admins can view orders"
on public.orders for select
using (exists (select 1 from public.admin_users where user_id = auth.uid()));

create policy "Admins can update orders"
on public.orders for update
using (exists (select 1 from public.admin_users where user_id = auth.uid()))
with check (exists (select 1 from public.admin_users where user_id = auth.uid()));

create policy "Admins can view order items"
on public.order_items for select
using (exists (select 1 from public.admin_users where user_id = auth.uid()));

create policy "Public can create order requests"
on public.order_requests for insert
with check (true);

create policy "Admins can view order requests"
on public.order_requests for select
using (exists (select 1 from public.admin_users where user_id = auth.uid()));

create policy "Admins can update order requests"
on public.order_requests for update
using (exists (select 1 from public.admin_users where user_id = auth.uid()))
with check (exists (select 1 from public.admin_users where user_id = auth.uid()));

create policy "Admins can view their own admin record"
on public.admin_users for select
using (user_id = auth.uid());

create policy "Public can view Instagram settings"
on public.site_settings for select
using (key = 'instagram_links');

create policy "Admins can manage products"
on public.products for all
using (exists (select 1 from public.admin_users where user_id = auth.uid()))
with check (exists (select 1 from public.admin_users where user_id = auth.uid()));

create policy "Admins can manage Instagram settings"
on public.site_settings for all
using (exists (select 1 from public.admin_users where user_id = auth.uid()))
with check (exists (select 1 from public.admin_users where user_id = auth.uid()));

insert into public.site_settings (key, value)
values ('instagram_links', '["https://www.instagram.com/theyarnside.co/"]'::jsonb)
on conflict (key) do nothing;
