create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  category text not null,
  price_inr integer not null check (price_inr >= 0),
  image_url text,
  stock_quantity integer not null default 0 check (stock_quantity >= 0),
  is_new boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_email text,
  customer_phone text not null,
  delivery_address text not null,
  notes text,
  status text not null default 'new' check (status in ('new', 'contacted', 'payment_pending', 'paid', 'making', 'shipped', 'completed', 'cancelled')),
  total_inr integer not null default 0 check (total_inr >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id),
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price_inr integer not null check (unit_price_inr >= 0),
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

create policy "Public can view active products"
on public.products for select
using (is_active = true);

create policy "Public can create orders"
on public.orders for insert
with check (true);

create policy "Public can create order items"
on public.order_items for insert
with check (true);

create index products_category_idx on public.products(category);
create index products_active_idx on public.products(is_active);
create index orders_status_idx on public.orders(status);
create index order_items_order_id_idx on public.order_items(order_id);
