create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  category text not null,
  price_inr integer not null check (price_inr >= 0),
  image_url text,
  image_urls jsonb not null default '[]'::jsonb,
  dimensions text,
  weight_grams integer check (weight_grams is null or weight_grams >= 0),
  stock_quantity integer not null default 0 check (stock_quantity >= 0),
  is_new boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_email text,
  customer_phone text not null,
  delivery_address text not null,
  notes text,
  status text not null default 'new' check (status in ('new', 'contacted', 'payment_pending', 'paid', 'making', 'shipped', 'completed', 'cancelled')),
  total_inr integer not null default 0 check (total_inr >= 0),
  pickup_status text not null default 'not_requested' check (pickup_status in ('not_requested', 'requested', 'picked_up')),
  pickup_requested_at timestamptz,
  shiprocket_order_id text,
  shiprocket_shipment_id text,
  awb_code text,
  courier_name text,
  tracking_url text,
  stock_restored_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id),
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price_inr integer not null check (unit_price_inr >= 0),
  created_at timestamptz not null default now()
);

create table public.order_requests (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  customer_name text not null,
  phone text not null,
  shipping_address text not null,
  budget_inr integer not null check (budget_inr >= 0),
  timeframe text not null check (timeframe in ('2_weeks', '3_weeks', '4_weeks', '5_weeks', 'take_your_time')),
  notes text,
  policy_version text,
  policy_accepted_at timestamptz,
  status text not null default 'new' check (status in ('new', 'contacted', 'accepted', 'declined', 'completed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

create policy "Public can view active products"
on public.products for select
using (is_active = true);

create policy "Public can create orders"
on public.orders for insert
with check (true);

create policy "Public can create order items"
on public.order_items for insert
with check (true);

create index products_category_idx on public.products(category);
create index products_active_idx on public.products(is_active);
create index orders_status_idx on public.orders(status);
create index order_items_order_id_idx on public.order_items(order_id);
create index order_requests_status_idx on public.order_requests(status);
create index order_requests_created_at_idx on public.order_requests(created_at);

create table public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table public.site_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;
alter table public.site_settings enable row level security;

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = excluded.public;

create policy "Admins can upload product images"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'product-images'
  and exists (select 1 from public.admin_users where user_id = auth.uid())
);

create policy "Admins can update product images"
on storage.objects for update to authenticated
using (
  bucket_id = 'product-images'
  and exists (select 1 from public.admin_users where user_id = auth.uid())
)
with check (
  bucket_id = 'product-images'
  and exists (select 1 from public.admin_users where user_id = auth.uid())
);

create policy "Admins can delete product images"
on storage.objects for delete to authenticated
using (
  bucket_id = 'product-images'
  and exists (select 1 from public.admin_users where user_id = auth.uid())
);

create policy "Admins can view orders"
on public.orders for select
using (exists (select 1 from public.admin_users where user_id = auth.uid()));

create policy "Admins can update orders"
on public.orders for update
using (exists (select 1 from public.admin_users where user_id = auth.uid()))
with check (exists (select 1 from public.admin_users where user_id = auth.uid()));

create policy "Admins can view order items"
on public.order_items for select
using (exists (select 1 from public.admin_users where user_id = auth.uid()));

create policy "Public can create order requests"
on public.order_requests for insert
with check (true);

create policy "Admins can view order requests"
on public.order_requests for select
using (exists (select 1 from public.admin_users where user_id = auth.uid()));

create policy "Admins can update order requests"
on public.order_requests for update
using (exists (select 1 from public.admin_users where user_id = auth.uid()))
with check (exists (select 1 from public.admin_users where user_id = auth.uid()));

create policy "Admins can view their own admin record"
on public.admin_users for select
using (user_id = auth.uid());

create policy "Public can view Instagram settings"
on public.site_settings for select
using (key = 'instagram_links');

create policy "Admins can manage products"
on public.products for all
using (exists (select 1 from public.admin_users where user_id = auth.uid()))
with check (exists (select 1 from public.admin_users where user_id = auth.uid()));

create policy "Admins can manage Instagram settings"
on public.site_settings for all
using (exists (select 1 from public.admin_users where user_id = auth.uid()))
with check (exists (select 1 from public.admin_users where user_id = auth.uid()));

insert into public.site_settings (key, value)
values ('instagram_links', '["https://www.instagram.com/theyarnside.co/"]'::jsonb)
on conflict (key) do nothing;

create or replace function public.create_order(
  p_customer_name text,
  p_customer_email text,
  p_customer_phone text,
  p_delivery_address text,
  p_notes text,
  p_policy_version text,
  p_policy_accepted_at timestamptz,
  p_items jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order_id bigint;
  v_item jsonb;
  v_product public.products%rowtype;
  v_quantity integer;
  v_total integer := 0;
begin
  if nullif(trim(p_policy_version), '') is null or p_policy_accepted_at is null then
    raise exception 'Returns, Refunds & Order Policy must be accepted';
  end if;
  if p_items is null or jsonb_array_length(p_items) = 0 then
    raise exception 'Cart cannot be empty';
  end if;

  insert into public.orders (customer_name, customer_email, customer_phone, delivery_address, notes, policy_version, policy_accepted_at, total_inr)
  values (trim(p_customer_name), nullif(trim(p_customer_email), ''), trim(p_customer_phone), trim(p_delivery_address), nullif(trim(p_notes), ''), trim(p_policy_version), p_policy_accepted_at, 0)
  returning id into v_order_id;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_quantity := (v_item->>'quantity')::integer;
    if v_quantity is null or v_quantity < 1 then
      raise exception 'Invalid item quantity';
    end if;

    select * into v_product
    from public.products
    where id = (v_item->>'product_id')::bigint
      and is_active = true
    for update;

    if not found then
      raise exception 'Product is no longer available';
    end if;
    if v_product.stock_quantity < v_quantity then
      raise exception 'Not enough stock for %', v_product.name;
    end if;

    update public.products
    set stock_quantity = stock_quantity - v_quantity,
        updated_at = now()
    where id = v_product.id;

    insert into public.order_items (order_id, product_id, product_name, quantity, unit_price_inr)
    values (v_order_id, v_product.id, v_product.name, v_quantity, v_product.price_inr);
    v_total := v_total + (v_product.price_inr * v_quantity);
  end loop;

  update public.orders set total_inr = v_total, updated_at = now() where id = v_order_id;
  return v_order_id;
end;
$$;

grant execute on function public.create_order(text, text, text, text, text, text, timestamptz, jsonb) to anon, authenticated;

create or replace function public.cancel_order(p_order_id bigint)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders%rowtype;
  v_item public.order_items%rowtype;
begin
  if not exists (select 1 from public.admin_users where user_id = auth.uid()) then
    raise exception 'Only admins can cancel orders';
  end if;

  select * into v_order from public.orders where id = p_order_id for update;
  if not found then
    raise exception 'Order not found';
  end if;

  if v_order.stock_restored_at is null then
    for v_item in select * from public.order_items where order_id = p_order_id loop
      update public.products
      set stock_quantity = stock_quantity + v_item.quantity,
          updated_at = now()
      where id = v_item.product_id;
    end loop;

    update public.orders
    set status = 'cancelled',
        stock_restored_at = coalesce(stock_restored_at, now()),
        updated_at = now()
    where id = p_order_id
    returning * into v_order;
  end if;

  return v_order;
end;
$$;

revoke execute on function public.cancel_order(bigint) from public, anon;
grant execute on function public.cancel_order(bigint) to authenticated;
