"use client";

import Link from "next/link";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import CartDrawer from "@/components/CartDrawer";
import CartBag from "@/components/CartBag";
import { CartProvider } from "@/components/CartProvider";

const POLICY_VERSION = "2026-08-26";

export default function ReturnsRefundsPolicyPage() {
  return <CartProvider><Header /><main className="policy-page">
    <section className="policy-hero"><p className="policy-eyebrow">THE YARN SIDE · POLICY</p><h1>Returns, refunds<br /><em>& order policy.</em></h1><p>We make each piece by hand and want every order to feel thoughtful, clear, and fair. This policy explains what happens when plans change and what we do when something genuinely goes wrong.</p><span>Policy version: {POLICY_VERSION}</span></section>
    <article className="policy-content">
      <section><h2>1. Cancellation</h2><p>Standard ready-to-ship orders may be cancelled before dispatch. Once an order has shipped, cancellation is no longer available.</p><p>For made-to-order or custom pieces, cancellation is allowed only before production begins. Once materials have been allocated or work has started, the order becomes non-cancellable.</p></section>
      <section><h2>2. Returns</h2><p>Returns are accepted for items that are damaged, defective, materially incorrect, or different from the product agreed or shown in the listing.</p><p>Please contact us within 48 hours of delivery with clear photos and any other helpful evidence. An unboxing video is welcome where available, but it is not the only evidence we may consider.</p></section>
      <section><h2>3. Change of mind</h2><p>We do not accept returns for dislike of colour, change of preference, accidental ordering, or minor handmade variation where the item is materially consistent with its listing.</p><p>Small differences in stitch tension, dimensions, yarn texture, placement, and colour appearance are natural characteristics of handmade crochet and are not defects by themselves.</p></section>
      <section><h2>4. Custom and personalised items</h2><p>Custom items cannot be returned or exchanged for preference or fit reasons once they have been made to the approved specification. If a custom item arrives damaged, defective, or materially different from what was agreed, please contact us so we can resolve it.</p><p>Design, colour, dimensions, and price are confirmed before production. Changes requested after production begins are at our discretion and may involve an additional charge.</p></section>
      <section><h2>5. Refunds and exchanges</h2><p>After a return or issue is approved and any necessary inspection is complete, an approved refund is returned to the original payment method. We aim to process refunds within 5–10 business days after approval; your bank or payment provider may take additional time.</p><p>Original shipping is refunded when the issue was caused by us or the item arrived defective or incorrect. We do not offer general exchanges initially. Replacement or exchange is available for verified damaged, defective, or incorrect products.</p></section>
      <section><h2>6. Address errors and refused parcels</h2><p>If an incorrect or incomplete address supplied by the customer causes a parcel to return to us, the customer is responsible for the re-shipping charge. If the customer does not want the parcel re-shipped, any eligible refund may exclude unrecoverable shipping and return-to-origin charges.</p><p>The same approach applies when a parcel is refused without an error on our part, provided the item returns safely to us.</p></section>
      <section><h2>7. Transit damage or missing delivery</h2><p>For transit damage, contact us within 48 hours with photos or other evidence. We will coordinate the courier claim ourselves and, after verification, arrange a replacement or refund where appropriate.</p><p>If tracking says delivered but the parcel is missing, contact us promptly, ideally within 24–48 hours. We will first review the tracking and delivery proof with the courier before deciding the resolution.</p></section>
      <section><h2>8. Custom timelines</h2><p>Custom-order timelines are estimates based on the current queue, materials, and design complexity. We provide an estimated production window rather than a guaranteed date unless we specifically confirm a guaranteed date.</p></section>
      <section className="policy-contact"><h2>Need help?</h2><p>Send us your order number, a short description of the issue, and photos where relevant. We will review the request and guide you through the next step.</p><Link href="/#custom-orders">Contact THE YARN SIDE →</Link></section>
    </article>
  </main><Footer /><CartDrawer /><CartBag /><style jsx global>{`.policy-page{background:var(--cream);color:var(--cocoa)}.policy-hero{padding:76px 24px 68px;background:var(--sage-light);border-bottom:1px solid rgba(75,58,50,.1)}.policy-hero>*{max-width:900px;margin-left:auto;margin-right:auto}.policy-eyebrow{margin-top:0;color:var(--coral);font:700 11px var(--font-lato),sans-serif;letter-spacing:.16em;text-transform:uppercase}.policy-hero h1{margin-top:10px;margin-bottom:18px;font:400 clamp(40px,6vw,70px)/1.05 var(--font-playfair),Georgia,serif}.policy-hero h1 em{color:var(--coral);font-style:normal}.policy-hero p:not(.policy-eyebrow){color:rgba(75,58,50,.72);font-size:17px;line-height:1.7}.policy-hero span{display:block;margin-top:20px;color:rgba(75,58,50,.58);font-size:12px}.policy-content{max-width:900px;margin:0 auto;padding:62px 24px 90px}.policy-content section{padding:28px 0;border-bottom:1px solid rgba(75,58,50,.12)}.policy-content section:first-child{padding-top:0}.policy-content h2{margin:0 0 12px;font:400 27px var(--font-playfair),Georgia,serif}.policy-content p{margin:0 0 12px;color:rgba(75,58,50,.75);font-size:15px;line-height:1.75}.policy-content p:last-child{margin-bottom:0}.policy-contact{padding:30px!important;margin-top:28px;border:0!important;border-left:3px solid var(--coral)!important;background:var(--white)}.policy-contact a{display:inline-block;margin-top:8px;color:var(--coral);font-weight:700}.policy-contact a:hover{color:var(--cocoa)}@media(max-width:600px){.policy-hero{padding:54px 18px}.policy-content{padding:44px 18px 64px}.policy-content h2{font-size:24px}}`}</style></CartProvider>;
}
