-- Bespoke inquiries from the custom-orders form, plus a shared accept/reject
-- workflow for both inquiries and out-of-stock order requests.

create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  email text not null,
  category text not null,
  details text not null,
  status text not null default 'new' check (
    status in ('new', 'accepted', 'rejected', 'in_progress', 'completed', 'packed', 'shipped', 'cancelled')
  ),
  admin_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists inquiries_status_idx on public.inquiries(status);
create index if not exists inquiries_created_at_idx on public.inquiries(created_at);

alter table public.inquiries enable row level security;

drop policy if exists "Public can create inquiries" on public.inquiries;
create policy "Public can create inquiries"
on public.inquiries for insert
with check (true);

drop policy if exists "Admins can view inquiries" on public.inquiries;
create policy "Admins can view inquiries"
on public.inquiries for select
using (exists (select 1 from public.admin_users where user_id = auth.uid()));

drop policy if exists "Admins can update inquiries" on public.inquiries;
create policy "Admins can update inquiries"
on public.inquiries for update
using (exists (select 1 from public.admin_users where user_id = auth.uid()))
with check (exists (select 1 from public.admin_users where user_id = auth.uid()));

-- Bring order_requests onto the same status vocabulary.
-- Legacy values: 'contacted' folds back to 'new', 'declined' becomes 'rejected'.
update public.order_requests set status = 'new' where status = 'contacted';
update public.order_requests set status = 'rejected' where status = 'declined';

alter table public.order_requests drop constraint if exists order_requests_status_check;
alter table public.order_requests add constraint order_requests_status_check check (
  status in ('new', 'accepted', 'rejected', 'in_progress', 'completed', 'packed', 'shipped', 'cancelled')
);

notify pgrst, 'reload schema';
